map $http_user_agent $is_bot {
    default 0;
    "~*Discordbot" 1;
    "~*facebookexternalhit" 1;
    "~*Twitterbot" 1;
}

server {
    listen 80;

	root /usr/share/nginx/html;

	gzip on;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;
    gzip_proxied any;

	location /images/ {
        expires 7d;
        add_header Cache-Control "public";
    }

	location /api/ {
        proxy_pass $BACKEND_URL/;
		proxy_http_version 1.1;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;

		proxy_cache_bypass $http_upgrade;
    }

	location / {
        if ($is_bot) {
            proxy_pass $BACKEND_URL/render-embed$request_uri;
            break;
        }

        try_files $uri $uri/ /index.html;
    }
}