// This file was generated by Prisma
import { defineConfig } from "prisma/config";

export default defineConfig({
	schema: "backend/database/schema.prisma",
	migrations: {path: "backend/database/migrations"},
	datasource: {url: Bun.env.DATABASE_URL},
});
