// This file was generated by Prisma
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Needed due to Prisma VS Code Extension always complaining
// TODO: add support for other environment file names
config({path: ["../.env.local"]});

export default defineConfig({
  schema: "schema.prisma",
  migrations: {path: "migrations"},
  datasource: {url: process.env.DATABASE_URL}
});
