import React from "react";
import { Fragment, type JSX } from "react";
import { Link, type Location, useLocation } from "react-router-dom";

// TODO: automatically populate this. maybe through a lookup actually generated by the actual pages? idk
const pageMap: {}[] = [{id: "Main", url: "/", name: "Main"}, {id: "AboutMe", url: "/aboutMe", name: "About Me"}, {
	id: "Projects",
	url: "/projects",
	name: "Projects",
}, {id: "Socials", url: "/socials", name: "Socials"}];

export default function NavigationBar(): JSX.Element
{
	const location: Location = useLocation();

	const navigationElements: JSX.Element[] = pageMap.map((data: any, index: number, array: {}[]) =>
	{
		const isSelected: boolean = location.pathname == data.url;

		var navElement: React.ReactNode = <a>{data.name}</a>;
		if (!isSelected) navElement = <Link className="yellow" to={data.url}>{data.name}</Link>;

		return <Fragment key={data.id}>[{navElement}]{index < array.length - 1 && " "}</Fragment>;
	});

	return (
		<nav>
			<h2 className="centered" style={{fontWeight: "normal"}}>{navigationElements}</h2>
		</nav>
	);
}
