import React from "react";
import { Fragment, type JSX, useState } from "react";

// TODO: automatically populate this. maybe through a lookup actually generated by the actual pages? idk
const pageMap: {}[] = [{id: "Main", name: "Main"}, {id: "AboutMe", name: "About Me"}, {
	id: "Projects",
	name: "Projects",
}, {id: "Socials", name: "Socials"}];

export default function NavigationBar(): JSX.Element
{
	const [curSelected, changeItem] = useState(0);

	const navigationElements: JSX.Element[] = pageMap.map((data: any, index: number, array: {}[]) =>
	{
		const isSelected: boolean = curSelected == index;

		function onClick(event: React.MouseEvent<HTMLAnchorElement, MouseEvent>): void
		{
			event.preventDefault();
			changeItem(index);
		}

		return (
			<Fragment>
				[
				<a
					className={!isSelected ? "yellow" : undefined}
					href={!isSelected ? "#" : undefined}
					onClick={!isSelected ? onClick : undefined}
				>
					{data.name}
				</a>
				]
				{index < array.length - 1 && " "}
			</Fragment>
		);
	});

	return (
		<div id="navigationBar">
			<h2 className="centered" style={{fontWeight: "normal"}}>{navigationElements}</h2>
		</div>
	);
}
